import {
    BASE_URL,
    PLAYERS,
    MATCHES,
    HEROES,
    ID,
    SLASH,
    HERO_URL,
    HERO_BY_ID_URL,
    ALL_HEROES_URL,
    MATCH_URL,
    MATCH_BY_ID_URL,
    ALL_MATCH_PLAYERS_BY_MATCH_ID_URL,
    ALL_MATCH_HEROES_BY_MATCH_ID_URL,
    MATCH_WINNER_BY_MATCH_ID_URL,
    PLAYER_URL,
    LAST_PLAYER_MATCH_BY_STEAM_ID_URL,
    FIXED_NUMBER_PLAYER_MATCHES,
    STEAM_ID,
    PATH_TO_MAIN_PAGE,
    PATH_TO_MATCHES_PAGE,
} from './Constants'

import {secondsToMinutesConverter} from './SecondsConverter'
import {calculateCurrentEntitiesViaPagePagination} from './EntityCalculator'

export {
    BASE_URL,
    PLAYERS,
    MATCHES,
    HEROES,
    ID,
    SLASH,
    HERO_URL,
    HERO_BY_ID_URL,
    ALL_HEROES_URL,
    MATCH_URL,
    MATCH_BY_ID_URL,
    ALL_MATCH_PLAYERS_BY_MATCH_ID_URL,
    ALL_MATCH_HEROES_BY_MATCH_ID_URL,
    MATCH_WINNER_BY_MATCH_ID_URL,
    PLAYER_URL,
    LAST_PLAYER_MATCH_BY_STEAM_ID_URL,
    FIXED_NUMBER_PLAYER_MATCHES,
    STEAM_ID,
    PATH_TO_MAIN_PAGE,
    PATH_TO_MATCHES_PAGE,
    secondsToMinutesConverter,
    calculateCurrentEntitiesViaPagePagination
}